#!/bin/bash

echo
echo -e "\e[1;37mAUTHOUR NAME : \e[1;4;91mARUN K BIJU\e[0m"
echo -e

echo -e "\e[1;37mTOOL NAME : \e[1;4;91mADB-Toolkit\e[0m"
echo -e

echo -e "\e[1;37mDATE : \e[1;91m19/04/2025\e[0m"
echo -e

echo -e "\e[1;37mGITHUB : \e[1;91mhttps://github.com/ArunKBiju\e[0m"
echo -e

echo -e "\e[1;37mNOTE : \e[1;91mPlease don't use for wrong intension just use for educational purpose cause its an educational tool.\e[0m"
echo -e

echo -e "\e[1;37mWRITTEN LANGUAGE : \e[1;91mBASH\e[0m"
echo
echo
echo
bash modules/funtion.sh
